### ISSUE TITLE
Continue if client_id cannot be fetched

### ISSUE THREAD

**Issue by martymcguire** [Taproot/indieauth#14]
[4.2 Client Information Discovery](https://indieauth.spec.indieweb.org/#client-information-discovery) states that authorization servers _SHOULD_ fetch `client_id` URLs (with some caveats) and that clients _SHOULD_ have a page at that URL, but neither is required.

Currently, Taproot/indieauth dies with an exception if `client_id` cannot be DNS resolved or fetched.

My preference would be for this info to "bubble up" as a warning on the authorization page rather than treating these as a hard failure.

**Comment by barnabywalters** [comment]
Personally I think I’d be very suspicious of any service where the `client_id` isn’t fetchable, but in the interest of following the spec and making a generally useful library, I agree that this would be better as a warning. Users can always customise the authorization page to prevent or discourage authorization in the event of an unfetchable `client_id` if they want.

**Comment by barnabywalters** [comment]
As of this update:

* If client_id and redirect_uri don’t share the same scheme, host name and protocol, a failure to fetch client_id is still a hard fail
* Otherwise, failing to fetch client_id will show the authorization form page, and pass an `$exception` variable to the template containing the raw exception thrown during fetching. The auth form can do whatever it wants with this. The default form just displays a warning paragraph, and the classname and message from the exception.
